# Copyright © 2017 ChaiShushan <chaishushan{AT}gmail.com>.
# License: https://creativecommons.org/licenses/by-nc-sa/4.0/

default:
	cd number && make
	go run main.go

clean:
	-cd number && make clean
	-rm *.a
	-rm a.out
