name: mdbook
on:
  push:
    branches:
      - main
      - master
      - "releases/*"
  pull_request:
    branches:
      - main
      - master
    types:
    - closed
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'
      - run: sudo apt update && sudo apt install chromium-browser wget unzip -y
      - run: |
          export mdbook_download_url=$(curl -s 'https://api.github.com/repos/HollowMan6/mdbook-pdf/releases?per_page=1&page=1' | python3 -c "import sys, json;import pprint;tmp=[print(x['browser_download_url']) if 'x86_64-unknown-linux-gnu' in x['name'] else None for x in json.load(sys.stdin)[0]['assets']]")
          wget $mdbook_download_url
          unzip mdbook*.zip
          rm mdbook*.zip
          chmod +x mdbook-pdf
          sudo mv mdbook-pdf /bin
      - run: mdbook build && ls -l book/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: test.pdf
          # A file, directory or wildcard pattern that describes what to upload
          path: book/pdf/output.pdf
          # The desired behavior if no files are found using the provided path.

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MY_DEPLOY_KEY }}
          publish_dir: ./book
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
